/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4206)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [Football]    Script Date: 11/3/2017 11:38:12 PM ******/
CREATE DATABASE [Football]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Football', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.DEVSQL\MSSQL\DATA\Football.mdf' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Football_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.DEVSQL\MSSQL\DATA\Football_log.ldf' , SIZE = 524288KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Football] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Football].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Football] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Football] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Football] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Football] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Football] SET ARITHABORT OFF 
GO

ALTER DATABASE [Football] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Football] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Football] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Football] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Football] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Football] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Football] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Football] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Football] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Football] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Football] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Football] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Football] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Football] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Football] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Football] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Football] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Football] SET RECOVERY FULL 
GO

ALTER DATABASE [Football] SET  MULTI_USER 
GO

ALTER DATABASE [Football] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Football] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Football] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Football] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Football] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Football] SET QUERY_STORE = OFF
GO

USE [Football]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Football] SET  READ_WRITE 
GO


